image: cypress/base
cypress-e2e:
  script:
    - npm install --save-dev cypress@3.0.2
    - npm i --save-dev react
    - npm i --save-dev enzyme enzyme-adapter-react-16
    - npm install eslint --save-dev
    - npm install eslint-plugin-react --save-dev
    - npm install eslint-plugin-cypress --save-dev
    - npm install cypress-eslint-preprocessor --save-dev
    - npm install --save-dev eslint-plugin-chai-friendly
    - npm start&
    - $(npm bin)/cypress run --record --key 92213f49-6b80-47d5-bbef-2422f308ebf1
    - ./node_modules/.bin/eslint ./src/components/**
   
    

    
    
   