image: docker:stable
variabes:
  DOCKER_DRIVER: overlay2
services:
- docker:dind
before_script:
- docker info

cypress-e2e:
  stage: build
  script:
    -  docker login -u steinko -p DavidBowie1!
  
    -  docker  build  -t steinko/app-productlib:1 -f Dockerfile.app .
    -  docker  push steinko/app-productlib:1
    
    -  docker build -t steinko/cypress-productlib:1 -f Dockerfile.cypress .
    -  docker push steinko/cypress-productlib:1
   
    -  kubectl apply -f app-pod.yaml
    -  kubectl apply -f app-deployment.yaml
    -  kubectl apply -f app-service.yaml
    -  kubectl apply -f cypress-pod.yaml
    -  kubectl apply -f cypress-job.yaml  
    
    
   