language: node_js
node_js:
- lts/*
addons:
  sonarcloud: 
before_script:
- npm install --save-dev cypress@3.0.2
- npm i --save-dev react
- npm i --save-dev enzyme enzyme-adapter-react-16
- npm i --save-dev webpack
- npm i --save-dev webpack-cli
- npm i --save-dev babel-core
- npm i --save-dev babel-preset-env
- npm i --save-dev babel-preset-react
- npm i --save-dev babel-loader
- npm i --save-dev babel-plugin-transform-class-properties
- npm i --save-dev babel-preset-flow
- npm i --save-dev flow-bin
- npm i --save-dev webpack-preprocessor
- npm i --save-dev html-webpack-plugin html-loader
- npm i --save-dev image-webpack-loader 
- npm i --save-dev file-loader 
- npm i --save-dev eslint
- npm i --save-dev eslint-plugin-react
- npm i --save-dev eslint-plugin-cypress 
- npm i --save-dev eslint-loader
- npm i --save-dev eslint-plugin-chai-friendly
- npm i --save-dev instanbul
- npm i --save-dev istanbul-instrumenter-loader
- npm start -- --silent &
script:
- $(npm bin)/cypress run
- sonar-scanner   -Dsonar.projectKey=productlib   -Dsonar.organization=steinko-github   -Dsonar.sources=./src/components   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=7658edeb2b312864ba1605433ea98e74f2a6aaa2