apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    pod: app-pod
spec:
  image: steinko/app-productlib:1
  ports:
    port: 3000
    protocol: TCP
  selector:
    service: app-service
