apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-pod-lable
  template:
    metadata:
      labels:
        app: app-pod-lable
    spec:
      containers:
      - name: app-container
        image: steinko/app-productlib:1
        ports:
        - containerPort: 3000
      