apiVersion: v1
kind: Pod
metadata:
   name: app-pod
   label: 
      pod:app-pod
spec: 
  containers:
     - image: steinko/app-productlib:1
       name: app
       ports: 
         - containerPort: 3000
       name: http
       protocol: TCP