apiVersion: v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      pod: app-pod
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: app-pod
    spec:
      containers:
      - image: steinko/app-productlib:1
        name: app
        ports:
        - containerPort: 3000
      