apiVersion: v1
kind: Pod
metadata:
   name: app-pod
   labels: 
      app: app-pod-lable
spec: 
  restartPolicy: Never
  containers:
     - name: app-container
       image: steinko/app-productlib:1
       readinessProbe:
         httpGet:
           port: 3000
         initialDelaySeconds: 5
         timeoutSeconds: 1
         periodSeconds: 10
         failureThreshold: 3
       ports:
       - containerPort: 3000
         name: http
         protocol: TCP
     
