version: '3'
services:
  app:
    build: 
      context: .
      dockerfile:  Dockerfile.app
    ports:
     - "3000:3000" 
  cypress:
    build: 
      context: .
      dockerfile: Dockerfile.cypress
    depends_on:
      - app